services:
  demo:
    image: kirillmedvedev/demo:1.0.2
    ports:
      - "8050:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mongodb
    volumes:
      - ./src/main/resources/application-docker.properties:/configuration/application-docker.properties
    networks:
      - myapp-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - myapp-network

networks:
  myapp-network:
    driver: bridge